apiVersion: v1
kind: Service
metadata:
  name: netflix-clone
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: netflix-clone