apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: netflix-clone
spec:
  type: {{ .Values.service.type }}
  selector:
    app: netflix-clone
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
