apiVersion: v1
kind: Service
metadata:
  name: netflix-clone
spec:
  type: {{ .Values.service.type }}
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
